# Generated by Django 5.2.8 on 2025-12-05 21:08

import django.db.models.deletion
import recrutement.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id_administration', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'administration")),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('type_administration', models.CharField(choices=[('ministere', 'Ministère'), ('agence', 'Agence'), ('collectivite', 'Collectivité territoriale'), ('etablissement', 'Établisssement public'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'administration")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse complète')),
            ],
            options={
                'verbose_name': 'Administration',
                'verbose_name_plural': 'Administrations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CandidatProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession actuelle')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('niveau_etude', models.CharField(blank=True, choices=[('bac', 'Baccalauréat'), ('bac+2', 'Bac+2'), ('bac+3', 'Licence'), ('bac+5', 'Master'), ('doctorat', 'Doctorat')], max_length=100, verbose_name="Niveau d'étude")),
                ('cv_default', models.FileField(blank=True, null=True, upload_to='cvs/default/%Y/%m/', verbose_name='CV par défaut')),
            ],
            options={
                'verbose_name': 'Profil candidat',
                'verbose_name_plural': 'Profils candidats',
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_nomination', models.DateField(auto_now_add=True, verbose_name='Date de nomination')),
            ],
            options={
                'verbose_name': 'Super Administrateur',
                'verbose_name_plural': 'Super Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='AdministrateurRH',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_RH', models.CharField(max_length=20, unique=True, verbose_name='ID RH')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('peut_valider', models.BooleanField(default=True, verbose_name='Peut valider les candidatures')),
                ('peut_publier', models.BooleanField(default=True, verbose_name='Peut publier des offres')),
                ('administration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrateurs_rh', to='recrutement.administration', verbose_name='Administration rattachée')),
            ],
            options={
                'verbose_name': 'Administrateur RH',
                'verbose_name_plural': 'Administrateurs RH',
            },
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id_adresse', models.AutoField(primary_key=True, serialize=False)),
                ('pays', models.CharField(default='Madagascar', max_length=100, verbose_name='Pays')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('rue', models.CharField(max_length=200, verbose_name='Rue')),
                ('complement_adresse', models.TextField(blank=True, verbose_name="Complément d'adresse")),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id_offre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('date_limite', models.DateField(verbose_name='Date limite de candidature')),
                ('grade', models.CharField(choices=[('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5')], max_length=20, verbose_name='Grade')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('pourvue', 'Pourvue'), ('expiree', 'Expirée')], default='brouillon', max_length=20, verbose_name="Statut de l'offre")),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('nombre_postes', models.PositiveIntegerField(default=1, verbose_name='Nombre de postes disponibles')),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire mensuel')),
                ('type_contrat', models.CharField(choices=[('CDD', 'Contrat à durée déterminée'), ('CDI', 'Contrat à durée indéterminée'), ('stage', 'Stage'), ('freelance', 'Freelance')], default='CDD', max_length=50, verbose_name='Type de contrat')),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='recrutement.administration', verbose_name='Administration')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur (RH)')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id_candidature', models.AutoField(primary_key=True, serialize=False)),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('delai_reponse', models.DateField(blank=True, null=True, verbose_name='Délai de réponse')),
                ('statut', models.CharField(choices=[('deposee', 'Déposée'), ('en_revue', 'En revue'), ('retenue', 'Retenue'), ('rejetee', 'Rejetée'), ('convoque', 'Convoqué'), ('embauche', 'Embauché')], default='deposee', max_length=20, verbose_name='Statut de la candidature')),
                ('cv', models.FileField(blank=True, null=True, upload_to=recrutement.models.cv_upload_path, verbose_name='Curriculum Vitae')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to=recrutement.models.lettre_upload_path, verbose_name='Lettre de motivation')),
                ('commentaire_rh', models.TextField(blank=True, verbose_name='Commentaire du RH')),
                ('commentaire_candidat', models.TextField(blank=True, verbose_name='Commentaire du candidat')),
                ('valide', models.BooleanField(default=False, verbose_name='Candidature validée')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrutement.offre', verbose_name='Offre')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_depot'],
                'unique_together': {('candidat', 'offre')},
            },
        ),
        migrations.CreateModel(
            name='CandidatFavoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.offre')),
            ],
            options={
                'verbose_name': 'Offre favorite',
                'verbose_name_plural': 'Offres favorites',
                'unique_together': {('candidat', 'offre')},
            },
        ),
    ]
