# Generated by Django 5.2.8 on 2026-01-02 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('cv_default', models.FileField(blank=True, null=True, upload_to='cvs/default/%Y/%m/', verbose_name='CV par défaut')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession actuelle')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('niveau_etude', models.CharField(blank=True, choices=[('bac', 'Baccalauréat'), ('bac+2', 'Bac+2'), ('bac+3', 'Licence'), ('bac+5', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=100, verbose_name="Niveau d'étude")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin_rh', 'Administrateur RH'), ('candidat', 'Candidat')], default='candidat', max_length=20, verbose_name='Rôle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rôle utilisateur',
                'verbose_name_plural': 'Rôles utilisateurs',
            },
        ),
    ]
