# Generated by Django 5.2.8 on 2026-01-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0002_userprofile_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='FR', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/%Y/%m/', verbose_name='Lettre de motivation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_upload_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de téléchargement du CV'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidat', 'Candidat'), ('rh', 'Ressources Humaines'), ('admin', 'Administrateur'), ('superadmin', 'Super Administrateur')], default='candidat', max_length=20, verbose_name='Rôle dans le système'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_role',
            field=models.CharField(choices=[('user', 'Utilisateur Normal'), ('rh', 'Ressources Humaines'), ('superadmin', 'Super Administrateur')], default='user', max_length=10, verbose_name='Rôle de connexion'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
