# Generated by Django 5.2.8 on 2026-01-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('niveau', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
