# Generated by Django 4.2.16 on 2026-01-28 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recrutement', '0004_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('offre', 'Nouvelle Offre'), ('candidature', 'Candidature'), ('statut', 'Changement de Statut'), ('message', 'Message'), ('system', 'Système')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('related_candidature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recrutement.candidature')),
                ('related_offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recrutement.offre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
